config/routes.rb
Rails.application.routes.draw do
  resources :results, only: [:create, :show]
  resources :queries, only: [:new, :create] do
    resources :results, only: [:new]
  end

  scope "/admin" do
    resources :queries, except: [:new, :create]
    resources :ethnicities
    resources :genders
    resources :results, except: [:new, :create, :show]
  end

  root "static_pages#home"

  get "/misgender-me", to: "queries#new"
  get "/feedback", to: "results#new"
  post "/submit-feedback", to: "results#create"
  patch "/submit-feedback", to: "results#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :query
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  ADMINS = { ENV["ADMIN_USERNAME"] => ENV["ADMIN_PASSWORD"] }

  before_action :authenticate, except: [:new, :create, :show]
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  def index
    @results = Result.all
  end

  def show
    @result = Result.find(params[:id])
    @result_data = JSON.parse(@result.returned_value)
  end

  def new
    @query = Query.find(params[:query_id])
    @returned_value = GenderMe.new(@query.username).result
    @result = Result.new
  end

  def edit
  end

  def create
    @query = Query.find(params[:query_id])
    @result = Result.new result_params

    if @result.save
      redirect_to @result, notice: "Your result was added to our database. Thank you for your feedback!"
    else
      render :new
    end
  end

  def update
    if @result.update(result_params)
      redirect_to @result, notice: "Result was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @result.destroy
    redirect_to results_url, notice: "Result was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_result
    @result = Result.find(params[:id])
    @query = Query.find(@result.query_id)
  end

  def authenticate
    authenticate_or_request_with_http_digest do |username|
      ADMINS[username]
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def result_params
    params.require(:result).permit(:accurate, :returned_value, :query_id)
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_with model: @result do |form| %>

  <div class="field">
    <%= form.label "How accurate were the algorithms in guessing your gender?" %> 
    <%= form.radio_button(:accurate, "Not accurate at all") %>
    <%= form.label "Not accurate at all" %>
    <%= form.radio_button(:accurate, "Somewhat accurate") %>
    <%= form.label "Somewhat accurate" %>
    <%= form.radio_button(:accurate, "Mostly accurate") %>
    <%= form.label "Mostly accurate" %>
    <%= form.radio_button(:accurate, "Completely accurate") %>
    <%= form.label "Completely accurate" %>
  </div>

    <%= form.hidden_field :returned_value, :value => @returned_value.to_json %>
    <%= form.hidden_field :query_id, :value => params[:query_id] %>
    <%= hidden_field_tag :query_id, params[:query_id] %>
  <div class="actions">
    <%= form.submit "Submit Feedback" %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table>
  <thead>
    <tr>
      <th>Accurate</th>
      <th>Returned result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
    
      <tr>
        <td><%= result.accurate %></td>
        <td><%= result.returned_value %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1> <%="Results for @#{@query.username}:"%></h1>
<br>
<p><strong>A facial recognition model would guess that the gender(s) in your profile picture are:</strong></p>
  <%- @returned_value[:face_gender].each do |result| %>
      <h3 id = result><%= "#{result}" %></h3>
  <% end %>
  <br>
<p><strong>Based on your display name, a name recognition model would guess that your gender is :</strong></p>
<h3 id = result><%=@returned_value[:name_gender]%></h3>
<br>
<p><strong>Based on your bio, a text analysis model would guess that your gender is :</strong></p>
<h3 id = result><%=@returned_value[:user_bio_gender]%><h3>
<br>
<p><strong>A text analysis model would guess that your tweets are :</strong></p>
<h3 id = result><%="#{@returned_value[:posts_gender][:male]} male and #{@returned_value[:posts_gender][:female]} female"%></h3>
<h2>Is that accurate?</h2>
<p>Help us collect data so we can better understand how gender and race affect the accuracy of these algorithms</p>
<%= render 'form' %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>
<h1> <%="Results for @#{@query.username}:"%></h1>
<br>
<p><strong>A facial recognition model would guess that the gender(s) in your profile picture are:</strong></p>
  <%- @result_data["face_gender"].each do |result| %>
      <h3 id = result><%= "#{result}" %></h3>
  <% end %>
  <br>
<p><strong>Based on your display name, a name recognition model would guess that your gender is :</strong></p>
<h3 id = result><%=@result_data["name_gender"]%></h3>
<br>
<p><strong>Based on your bio, a text analysis model would guess that your gender is :</strong></p>
<h3 id = result><%=@result_data["user_bio_gender"]%><h3>
<br>
<p><strong>A text analysis model would guess that your tweets are :</strong></p>
<h3 id = result><%="#{@result_data["posts_gender"]["male"]} male and #{@result_data["posts_gender"]["female"]} female"%></h3>



<%= link_to 'Try again', "/misgender-me" %>