config/routes.rb
Rails.application.routes.draw do
  resources :results, only: [:create, :show]
  resources :queries, only: [:new, :create] do
    resources :results, only: [:new]
  end

  scope "/admin" do
    resources :queries, except: [:new, :create]
    resources :ethnicities
    resources :genders
    resources :results, except: [:new, :create, :show]
  end

  root "static_pages#home"

  get "/misgender-me", to: "queries#new"
  get "/feedback", to: "results#new"
  post "/submit-feedback", to: "results#create"
  patch "/submit-feedback", to: "results#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord
  has_and_belongs_to_many :queries
end

app/controllers/ethnicities_controller.rb
class EthnicitiesController < ApplicationController
  ADMINS = { ENV["ADMIN_USERNAME"] => ENV["ADMIN_PASSWORD"] }

  before_action :authenticate

  before_action :set_ethnicity, only: [:show, :edit, :update, :destroy]

  # GET /ethnicities
  # GET /ethnicities.json
  def index
    @ethnicities = Ethnicity.all
  end

  # GET /ethnicities/1
  # GET /ethnicities/1.json
  def show
  end

  # GET /ethnicities/new
  def new
    @ethnicity = Ethnicity.new
  end

  # GET /ethnicities/1/edit
  def edit
  end

  # POST /ethnicities
  # POST /ethnicities.json
  def create
    @ethnicity = Ethnicity.new(ethnicity_params)

    respond_to do |format|
      if @ethnicity.save
        format.html { redirect_to @ethnicity, notice: "Ethnicity was successfully created." }
        format.json { render :show, status: :created, location: @ethnicity }
      else
        format.html { render :new }
        format.json { render json: @ethnicity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ethnicities/1
  # PATCH/PUT /ethnicities/1.json
  def update
    respond_to do |format|
      if @ethnicity.update(ethnicity_params)
        format.html { redirect_to @ethnicity, notice: "Ethnicity was successfully updated." }
        format.json { render :show, status: :ok, location: @ethnicity }
      else
        format.html { render :edit }
        format.json { render json: @ethnicity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ethnicities/1
  # DELETE /ethnicities/1.json
  def destroy
    @ethnicity.destroy
    respond_to do |format|
      format.html { redirect_to ethnicities_url, notice: "Ethnicity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ethnicity
    @ethnicity = Ethnicity.find(params[:id])
  end

  def authenticate
    authenticate_or_request_with_http_digest do |username|
      ADMINS[username]
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ethnicity_params
    params.require(:ethnicity).permit(:name)
  end
end

app/helpers/ethnicities_helper.rb
module EthnicitiesHelper
end

app/views/ethnicities/_form.html.erb
<%= form_with(model: ethnicity, local: true) do |form| %>
  <% if ethnicity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ethnicity.errors.count, "error") %> prohibited this ethnicity from being saved:</h2>

      <ul>
      <% ethnicity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ethnicities/edit.html.erb
<h1>Editing Ethnicity</h1>

<%= render 'form', ethnicity: @ethnicity %>

<%= link_to 'Show', @ethnicity %> |
<%= link_to 'Back', ethnicities_path %>

app/views/ethnicities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ethnicities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ethnicities.each do |ethnicity| %>
      <tr>
        <td><%= ethnicity.name %></td>
        <td><%= link_to 'Show', ethnicity %></td>
        <td><%= link_to 'Edit', edit_ethnicity_path(ethnicity) %></td>
        <td><%= link_to 'Destroy', ethnicity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ethnicity', new_ethnicity_path %>

app/views/ethnicities/new.html.erb
<h1>New Ethnicity</h1>

<%= render 'form', ethnicity: @ethnicity %>

<%= link_to 'Back', ethnicities_path %>

app/views/ethnicities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ethnicity.name %>
</p>

<%= link_to 'Edit', edit_ethnicity_path(@ethnicity) %> |
<%= link_to 'Back', ethnicities_path %>