config/routes.rb
Rails.application.routes.draw do
  resources :results, only: [:create, :show]
  resources :queries, only: [:new, :create] do
    resources :results, only: [:new]
  end

  scope "/admin" do
    resources :queries, except: [:new, :create]
    resources :ethnicities
    resources :genders
    resources :results, except: [:new, :create, :show]
  end

  root "static_pages#home"

  get "/misgender-me", to: "queries#new"
  get "/feedback", to: "results#new"
  post "/submit-feedback", to: "results#create"
  patch "/submit-feedback", to: "results#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/query.rb
class Query < ApplicationRecord
  has_and_belongs_to_many :genders
  has_and_belongs_to_many :ethnicities
  has_one :result

  accepts_nested_attributes_for :result, allow_destroy: true

  validates :username, presence: true
  validates :consent, acceptance: true
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  ADMINS = { ENV["ADMIN_USERNAME"] => ENV["ADMIN_PASSWORD"] }

  before_action :authenticate, except: [:new, :create, :show]
  before_action :set_query, only: [:show, :edit, :update, :destroy]

  def index
    @queries = Query.all
  end

  def new
    @query = Query.new
  end

  def edit
  end

  def create
    @query = Query.new(query_params)
    if @query.save
      redirect_to new_query_result_path(@query)
    else
      render :new
    end
  end

  def update
    if @query.update(query_params)
      redirect_to @query, notice: "Query was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @query.destroy
    redirect_to queries_url, notice: "Query was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_query
    @query = Query.find(params[:id])
  end

  def authenticate
    authenticate_or_request_with_http_digest do |username|
      ADMINS[username]
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def query_params
    params.require(:query).permit(:username, :consent, gender_ids: [], ethnicity_ids: [])
  end
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/_form.html.erb
      <ul>
      <% query.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

<%= form_with model: @query do |form| %>
  

  <div class="field">
    <%= form.label "Twitter handle:" %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
  <%= form.label "Which term(s), if any, best describes your gender?" %><br />
  <div class = "flex">
  <%= form.collection_check_boxes :gender_ids, Gender.all, :id, :name do |b| %>
    <div class="collection-check-box">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
  </div>

  <div class="field">
  <%= form.label "Which term(s), if any, best describes your ethnicity?" %><br />
  <div class = "flex">
  <%= form.collection_check_boxes :ethnicity_ids, Ethnicity.all, :id, :name do |b| %>
    <div class="collection-check-box">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
  </div>

  <div class="field">
    <p id="consent">This information will be used purely for research purposes for a TechTogether Boston project on gender and racial bias in machine learning. No identifying information will be shared outside of the project group at any point in time.</p>
    <%= form.label "I consent to my data being collected." %>
    <%= form.check_box :consent %>
  </div>

  <div class="actions">
    <%= form.submit "Misgender me"%>
  </div>
<% end %>

app/views/queries/edit.html.erb
<h1>Editing Query</h1>

<%= render 'form', query: @query %>

<%= link_to 'Show', @query %> |
<%= link_to 'Back', queries_path %>

app/views/queries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Queries</h1>

<table>
  <thead>
    <tr>
    <th>Username</th>
    <th>Gender ID</th>
      <th>Ethnicity ID</th>
      <th>Consent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @queries.each do |query| %>
      <tr>
        <td><%= query.username %></td>
        <td><%= query.gender_ids %></td>
        <td><%= query.ethnicity_ids %></td>
        <td><%= query.consent %></td>
        <td><%= link_to 'Show', query %></td>
        <td><%= link_to 'Edit', edit_query_path(query) %></td>
        <td><%= link_to 'Destroy', query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Query', new_query_path %>

app/views/queries/new.html.erb
<h1>Your information:</h1>

<%= render 'form', query: @query %>

<%= link_to 'Back', queries_path %>