config/routes.rb
Rails.application.routes.draw do
  resources :results, only: [:create, :show]
  resources :queries, only: [:new, :create] do
    resources :results, only: [:new]
  end

  scope "/admin" do
    resources :queries, except: [:new, :create]
    resources :ethnicities
    resources :genders
    resources :results, except: [:new, :create, :show]
  end

  root "static_pages#home"

  get "/misgender-me", to: "queries#new"
  get "/feedback", to: "results#new"
  post "/submit-feedback", to: "results#create"
  patch "/submit-feedback", to: "results#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_and_belongs_to_many :queries
end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
  ADMINS = { ENV["ADMIN_USERNAME"] => ENV["ADMIN_PASSWORD"] }

  before_action :authenticate
  before_action :set_gender, only: [:show, :edit, :update, :destroy]

  # GET /genders
  # GET /genders.json
  def index
    @genders = Gender.all
  end

  # GET /genders/1
  # GET /genders/1.json
  def show
  end

  # GET /genders/new
  def new
    @gender = Gender.new
  end

  # GET /genders/1/edit
  def edit
  end

  # POST /genders
  # POST /genders.json
  def create
    @gender = Gender.new(gender_params)

    respond_to do |format|
      if @gender.save
        format.html { redirect_to @gender, notice: "Gender was successfully created." }
        format.json { render :show, status: :created, location: @gender }
      else
        format.html { render :new }
        format.json { render json: @gender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genders/1
  # PATCH/PUT /genders/1.json
  def update
    respond_to do |format|
      if @gender.update(gender_params)
        format.html { redirect_to @gender, notice: "Gender was successfully updated." }
        format.json { render :show, status: :ok, location: @gender }
      else
        format.html { render :edit }
        format.json { render json: @gender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genders/1
  # DELETE /genders/1.json
  def destroy
    @gender.destroy
    respond_to do |format|
      format.html { redirect_to genders_url, notice: "Gender was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gender
    @gender = Gender.find(params[:id])
  end

  def authenticate
    authenticate_or_request_with_http_digest do |username|
      ADMINS[username]
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gender_params
    params.require(:gender).permit(:name)
  end
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/views/genders/_form.html.erb
<%= form_with(model: gender, local: true) do |form| %>
  <% if gender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gender.errors.count, "error") %> prohibited this gender from being saved:</h2>

      <ul>
      <% gender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genders/edit.html.erb
<h1>Editing Gender</h1>

<%= render 'form', gender: @gender %>

<%= link_to 'Show', @gender %> |
<%= link_to 'Back', genders_path %>

app/views/genders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genders.each do |gender| %>
      <tr>
        <td><%= gender.name %></td>
        <td><%= link_to 'Show', gender %></td>
        <td><%= link_to 'Edit', edit_gender_path(gender) %></td>
        <td><%= link_to 'Destroy', gender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gender', new_gender_path %>

app/views/genders/new.html.erb
<h1>New Gender</h1>

<%= render 'form', gender: @gender %>

<%= link_to 'Back', genders_path %>

app/views/genders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gender.name %>
</p>

<%= link_to 'Edit', edit_gender_path(@gender) %> |
<%= link_to 'Back', genders_path %>